### ISSUE TITLE
Parameters List

### ISSUE THREAD

**Issue by Zerawr123123** [KokoDevs/CreatorTools#20]
Hi, Is there a list of parameters that we can use?
I was hoping to know how to get the username of someone's donation, and use it as a Custom name for a mob
but I don't know the command/parameter for it.

maybe like {username} ?

example:
/execute as @p run summon minecraft:villager ~ ~ ~ {CustomName:"\"{username}\"",CustomNameVisible:1b}

**Comment by Zerawr123123** [comment]
nvm, I actually found out its {name} 
Thank you for this mod, I was searching for a mod like this anywhere like crazy

**Comment by KokoDevs** [comment]
Thank you for supporting and using this mod, glad you find your answer, if you have any related questions like this you can check our docs which contains stuff like this, and hopefully when me and Ben(Second developer) get more time on our hands we will update this mod for newer versions. 😄
